"""Add new tables and fields

Revision ID: 3a5621d9e77d
Revises: 9ddb38e17faf
Create Date: 2025-05-02 17:21:32.868269

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5621d9e77d'
down_revision: Union[str, None] = '9ddb38e17faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_make',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_make_slug'), 'car_make', ['slug'], unique=True)
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['car_make.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_model_make_id'), 'car_model', ['make_id'], unique=False)
    op.create_index(op.f('ix_car_model_slug'), 'car_model', ['slug'], unique=True)
    op.add_column('autoad', sa.Column('car_model_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_autoad_car_model_id'), 'autoad', ['car_model_id'], unique=False)
    op.create_foreign_key(None, 'autoad', 'car_model', ['car_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'autoad', type_='foreignkey')
    op.drop_index(op.f('ix_autoad_car_model_id'), table_name='autoad')
    op.drop_column('autoad', 'car_model_id')
    op.drop_index(op.f('ix_car_model_slug'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_make_id'), table_name='car_model')
    op.drop_table('car_model')
    op.drop_index(op.f('ix_car_make_slug'), table_name='car_make')
    op.drop_table('car_make')
    # ### end Alembic commands ###
