"""Initial create autoad tables

Revision ID: 9ddb38e17faf
Revises: 
Create Date: 2025-04-17 12:46:45.595575

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddb38e17faf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoad',
    sa.Column('id_ad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url_ad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currencyCode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gearbox', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('engine_capacity', sa.Integer(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engine_power', sa.Integer(), nullable=True),
    sa.Column('sellerLink', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_ad')
    )
    op.create_index(op.f('ix_autoad_id_ad'), 'autoad', ['id_ad'], unique=False)
    op.create_index(op.f('ix_autoad_url_ad'), 'autoad', ['url_ad'], unique=False)
    op.create_table('autoadhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_ad_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currencyCode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['auto_ad_id'], ['autoad.id_ad'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autoadhistory_auto_ad_id'), 'autoadhistory', ['auto_ad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autoadhistory_auto_ad_id'), table_name='autoadhistory')
    op.drop_table('autoadhistory')
    op.drop_index(op.f('ix_autoad_url_ad'), table_name='autoad')
    op.drop_index(op.f('ix_autoad_id_ad'), table_name='autoad')
    op.drop_table('autoad')
    # ### end Alembic commands ###
