"""Добавлено поле data_id в AutoAd

Revision ID: f27553e3d3fa
Revises: f08ef9b3a8cc
Create Date: 2025-02-02 13:55:54.471420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27553e3d3fa'
down_revision: Union[str, None] = 'f08ef9b3a8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autoad', sa.Column('data_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_autoad_data_id'), 'autoad', ['data_id'], unique=True)
    op.create_foreign_key(None, 'autoadhistory', 'autoad', ['auto_ad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'autoadhistory', type_='foreignkey')
    op.drop_index(op.f('ix_autoad_data_id'), table_name='autoad')
    op.drop_column('autoad', 'data_id')
    # ### end Alembic commands ###
